### ISSUE TITLE
Paloma 1.13.0 Release Checklist

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1425]
## Cleanup
- [x] Verify Pigeon changes, remove commented code and word PR
- [x] Verify Paloma changes, remove commented code, word PR
- [x] Verify test net repository changes and merge
- [x] Cherry pick Paloma v1.12.2 changes on to master
- [x] Update current migration `semver` solution to work with new changes

## Final test run on pvt test net
- [x] Complete test run books
- [x] Verify integration with all supported chains

## Maintenance
- [x] Update minimum version of pigeon
- [x] Write up migration guide (libwasmvm!)
- [x] Update READMEs

## Post release
- [ ] Retire `devel` branch, rebase content onto feature branch
- [ ] Dependabot
