### ISSUE TITLE
Refactor Gravity nonce implementation

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1636]
## Problem description

The original gravity code assumes a 1:1 relation between the local chain and the remote chain. Paloma, however, supports tokens across `n` chains, leaving us with a 1:`n` relationship. 

This causes headaches across the following areas:

- Paloma only keeps track of the latest observed nonce and latest observed block height for one chain, instead of `n`
- Paloma also keeps all attestations in one store, instead of one store per remote chain
- Attestation assumes that the observed nonces will always increase exactly by `1`, which they won't if they're shared between different chains
- Probably more that I don't see right now

This is the price we pay for not having written the module ourselves and just copied it over. To support our use case, I think we'd need one keeper per remote chain, but I don't think that's feasible with the Cosmos architecture. So instead, we need to hack what we have to support the `n` chain constraint.

## Action plan

- [x] Refactor Paloma gravity keeper to respect the contextual reference chain ID
  - [x] Last observed BH by chain
  - [x] Last observed nonce by chain
  - [x] Attestations by chain
  - [x] Last nonce by validator and chain
- [x] ~~Update Compass, `event_id` actually seems to be the `gravity_nonce`, but it's used throughout the board. Remove usages across other, non-gravity related functions and revert the last PR that added the second nonce. Also rename it to be more clear on intentions.~~
- [x] Update Paloma to work with the new compass, both payload & generative logic. We will keep a separate `event_id` for better traceability.

**Comment by taariq** [comment]
@byte-bandit this is fixed with https://github.com/palomachain/paloma/pull/1174 yes?

**Comment by byte-bandit** [comment]
Not completely. The last changes for this I"m still working on.
