### ISSUE TITLE
Redeploy Base compass with the new fee manager

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#2068]
### Background
Since we had deployed the fee manager on Base after deploying Compass, they cannot be linked. We therefore need to redeploy the fee manager and compass again by removing and adding support for Base chain. 

### Todo

- [x] Upload new fee manager
- [x] Submit vote to remove chain support for `base-main`
- [x] Wait until proposal passes and the chain is removed
- [x] Submit vote to support new chain
- [x] Wait until proposal passes and the chain is added
- [x] Submit vote to Paloma to register new fee manager for `base-main` against `0xeE8338Ee133B6705a7144a407eeB64Bf742B78f9`
- [x] Wait for vote to pass and contract to be deployed
- [x] Manually register compass with the fee manager

**Comment by byte-bandit** [comment]
New fee manager contract address: https://basescan.org/address/0xee8338ee133b6705a7144a407eeb64bf742b78f9

**Comment by verabehr** [comment]
@byte-bandit when the chain is added again, compass is deployed, doesn’t that mean that compass is again deployed before the fee manager is set?

**Comment by byte-bandit** [comment]
> @byte-bandit when the chain is added again, compass is deployed, doesn’t that mean that compass is again deployed before the fee manager is set?

No deployment will be created for chains that do not have the fee manager property set. When a new chain is created, this value is left empty initially. So even though the current chain has this property set, the new one won't have it, and no deployment will be created until the value has been populated.

**Comment by verabehr** [comment]
proposal to remove base chain https://paloma.explorers.guru/proposal/107

**Comment by taariq** [comment]
Waiting for the Fee Manager vote to pass for Base: https://paloma.explorers.guru/proposal/113

**Comment by taariq** [comment]
Accidentally deleted 113. Redid the vote with https://paloma.explorers.guru/proposal/116

**Comment by taariq** [comment]
@byte-bandit Base appears not to be added Shows still **IN_PROPOSAL** via `palomad q evm chains-infos --node https://rpc-1.paloma.nodes.guru`
```
- abi: ""
  activeSmartContractID: "0"
  bytecode: null
  chainID: "8453"
  chainReferenceID: base-main
  constructorInput: null
  id: "0"
  minOnChainBalance: "1000000"
  referenceBlockHash: 0xe8423ce3f8bb2dc392c116e9676b7069204bc83959e9bc5e60bc037f18a88629
  referenceBlockHeight: "19293160"
  relayWeights:
    executionTime: "1.0"
    featureSet: "1.0"
    fee: "1.0"
    successRate: "1.0"
    uptime: "1.0"
  smartContractAddr: ""
  smartContractUniqueID: null
  status: IN_PROPOSAL
```

**Comment by byte-bandit** [comment]
@taariq That's fine. It's waiting for the fee manager vote to land.

**Comment by taariq** [comment]
> @taariq That's fine. It's waiting for the fee manager vote to land.

FYI @webelf101
